In [1]:
import numpy as np

<h2>What is the difference between Scalars, Vectors, Matrices, and Tensors</h2>

A <b>scalar</b> is a single number. Scalars are typically written in lowercase and italics.<br />
A <b>vector</b> is an array of numbers. Vectors are typically written in lowercase, italics and bold type.<br />
A <b>matrix</b> is a 2-D array. Matrices are typically written in uppercase, italics, and bold.<br />
A <b>tensor</b> is a <i>n</i>-dimensional array with <i>n</i> > 2.

In [2]:
#Creating a row vector

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [94]:
#Creating a column vector

b = np.array([[1],
            [2],
            [3],
            [4]])
b

array([[1],
       [2],
       [3],
       [4]])

In [5]:
#Creating a (3x2) matrix with nested brackets

A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
#Shape command will tell you the dimensions, rows by columns

A.shape

(3, 2)

In [8]:
a.shape

(4,)

In [11]:
len(a)

4

<b>Describing arrays and matrices</b>

In [88]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
#View numbers of rows and columns

A.shape

(3, 2)

In [90]:
#View number of elements

A.size

6

In [91]:
#View number of dimensions

A.ndim

2

<b>Transposition can help you convert a row vector to a column vector, or reverse.</b>

In [28]:
#Create a vector and transpose it

a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [30]:
a_t = a.T
a_t

array([1, 2, 3, 4, 5, 6])

In [33]:
a.shape

(6,)

In [34]:
a_t.shape

(6,)

In [13]:
#Create a matrix and transpose it

A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
A.shape

(3, 2)

In [16]:
A_t.shape

(2, 3)

<b>Selecting Elements Within an Array</b>

In [39]:
#Creating a vector

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [36]:
a[0]

1

In [38]:
a[1]

2

In [40]:
a[2]

3

In [45]:
#Creating a matrix

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
A[0,0]

1

In [43]:
A[1,1]

5

In [46]:
A[2,2]

9

In [56]:
#Creating a tensor

B = np.array([
    [[2, 1], [1, 2]], 
     [[3, 4], [4, 3]],
    [[6, 5], [5, 6]], 
     [[8, 7], [7, 8]]])
B

array([[[2, 1],
        [1, 2]],

       [[3, 4],
        [4, 3]],

       [[6, 5],
        [5, 6]],

       [[8, 7],
        [7, 8]]])

In [66]:
#Selecting second-element of each of the dimensions
first = B[0][0][1]
second = B[1][0][1]
third = B[2][0][1]
fourth = B[3][0][1]

print(f"The values for the first set of dimensions is {first}, the second is {second}, third is {third},", 
      f"and fourth is {fourth}.")

The values for the first set of dimensions is 1, the second is 4, third is 5, and fourth is 7.


<b>Reshaping an Array</b>

In [75]:
#Creating a 4x matrix

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [76]:
A.shape

(4, 3)

In [77]:
#Reshaping into a 2x6

B = A.reshape(2,6)
B

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [78]:
B.shape

(2, 6)

In [79]:
#Flattening a matrix

C = A.flatten()
C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
C.shape

(12,)

<h2>Playing with Matrices</h2>

<b>Getting the Diagonal</b>

In [72]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
A.diagonal()

array([1, 5, 9])

<b>Finding the Max and Min</b>

In [81]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.max(A)

9

In [83]:
np.min(A)

1

In [87]:
#Max element by column

np.max(A, axis=0)

array([7, 8, 9])

In [86]:
#Max element by row

np.max(A, axis=1)

array([3, 6, 9])

<b>Calculating trace, determinant, average, variance, and standard deviation of a matrix</b>

In [95]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
#Trace

A.diagonal().sum()

15

In [97]:
#Determinant

np.linalg.det(A)

-9.51619735392994e-16

In [98]:
#Average

np.mean(A)

5.0

In [99]:
#Variance

np.var(A)

6.666666666666667

In [100]:
#Standard Deviation

np.std(A)

2.581988897471611

<b>Adding Matrices</b>

In [20]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
B = np.array([[7, 8], [9, 10], [11, 12]])
B

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
C = A + B
C

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [101]:
#Create a matrix and transpose it

A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
#Adding a constant to a matrix

C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
#Adding matrices of different shapes

D = np.array([[13, 14], [15, 16], [17, 18]])
D

array([[13, 14],
       [15, 16],
       [17, 18]])

In [26]:
E = np.array([[19], [20], [21]])
E

array([[19],
       [20],
       [21]])

In [27]:
F = D+E
F

array([[32, 33],
       [35, 36],
       [38, 39]])

In [105]:
#Other ways to add or subtract matrices

np.add(D, E)

array([[32, 33],
       [35, 36],
       [38, 39]])

In [106]:
np.subtract(D, E)

array([[-6, -5],
       [-5, -4],
       [-4, -3]])

<b>Dot Product of two Vectors</b>

In [102]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [103]:
np.dot(a, b)

32

In [104]:
a @ b

32

<b>Applying functions to Matrices and Vectors</b>

In [107]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
#Creates a function that adds 10

add_10 = lambda i: i + 10

In [112]:
#Creates a vectorized version of add_10

add_10_vectorized = np.vectorize(add_10)

In [113]:
add_10_vectorized(A)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])